//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-31 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap5/Address.vdmsl".

#ifndef _Address_h
#define _Address_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "Address_anonym.h"


void init_Address ();


#endif // _Address_h
