//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-31 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap5/Address.vdmsl".


#include "Address.h"


#ifdef DEF_Address_USERIMPL

#include "Address_userimpl.cpp"


#endif // DEF_Address_USERIMPL


void init_Address () {}

