//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-09-02 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap5/register.vdmsl".


#include "register.h"


#ifdef DEF_register_USERIMPL

#include "register_userimpl.cpp"


#endif // DEF_register_USERIMPL


void init_register () {}

#ifndef DEF_register_Add

TYPE_register_RegisterBook vdm_register_Add (const TYPE_register_Name &vdm_register_name, const TYPE_register_RegisterBook &vdm_register_book) {
  if (!vdm_register_pre_Add(vdm_register_name, vdm_register_book).GetValue()) {
    CGUTIL::RunTime(L"Precondition failure in Add");
  }
  return vdm_register_book.Union(mk_set(vdm_register_name));
}

#endif // DEF_register_Add

#ifndef DEF_register_pre_Add

Bool vdm_register_pre_Add (const TYPE_register_Name &vdm_register_name, const TYPE_register_RegisterBook &vdm_register_book) {
  return Bool(!vdm_register_book.InSet(vdm_register_name));
}

#endif // DEF_register_pre_Add

#ifndef DEF_register_Delete

TYPE_register_RegisterBook vdm_register_Delete (const TYPE_register_Name &vdm_register_name, const TYPE_register_RegisterBook &vdm_register_book) {
  if (!vdm_register_pre_Delete(vdm_register_name, vdm_register_book).GetValue()) {
    CGUTIL::RunTime(L"Precondition failure in Delete");
  }
  return vdm_register_book.Diff(mk_set(vdm_register_name));
}

#endif // DEF_register_Delete

#ifndef DEF_register_pre_Delete

Bool vdm_register_pre_Delete (const TYPE_register_Name &vdm_register_name, const TYPE_register_RegisterBook &vdm_register_book) {
  return Bool(vdm_register_book.InSet(vdm_register_name));
}

#endif // DEF_register_pre_Delete

#ifndef DEF_register_Number

Int vdm_register_Number (const TYPE_register_RegisterBook &vdm_register_book) {
  return Int(vdm_register_book.Card());
}

#endif // DEF_register_Number


