//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-09-02 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap5/register.vdmsl".

#ifndef _register_h
#define _register_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "register_anonym.h"


void init_register ();

TYPE_register_RegisterBook vdm_register_Add (const TYPE_register_Name &, const TYPE_register_Email &, const TYPE_register_RegisterBook &);

Bool vdm_register_pre_Add (const TYPE_register_Name &, const TYPE_register_Email &, const TYPE_register_RegisterBook &);

TYPE_register_RegisterBook vdm_register_Delete (const TYPE_register_Name &, const TYPE_register_RegisterBook &);

Bool vdm_register_pre_Delete (const TYPE_register_Name &, const TYPE_register_RegisterBook &);

Int vdm_register_Number (const TYPE_register_RegisterBook &);


#endif // _register_h
