//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/dec2bin.vdmsl".


#include "dec2bin.h"

#include "dec2bin_userimpl.cpp"


void init_dec2bin () {}

#ifndef DEF_dec2bin_pre_dec2bin

Bool vdm_dec2bin_pre_dec2bin (const Int &vdm_dec2bin_X) {
  return Bool(vdm_dec2bin_X.GetValue() >= 1);
}

#endif // DEF_dec2bin_pre_dec2bin

#ifndef DEF_dec2bin_post_dec2bin

Bool vdm_dec2bin_post_dec2bin (const Int &vdm_dec2bin_X, const type_iL &vdm_dec2bin_b) {
  bool tmpQuant_4 = true;
  const Set e1_set_7 (vdm_dec2bin_b.Inds());
  Set tmpSet_45 (e1_set_7);
  Generic tmpe_44;
  for (bool bb_43 = tmpSet_45.First(tmpe_44); bb_43 && tmpQuant_4; bb_43 = tmpSet_45.Next(tmpe_44)) {
    const Int vdm_dec2bin_i (tmpe_44);
    Bool pred_8;
    if (!((static_cast<Int>(vdm_dec2bin_b[vdm_dec2bin_i])).GetValue() == 1)) {
      Bool var2_14;
      Bool var1_15;
      if ((static_cast<Int>(vdm_dec2bin_b[vdm_dec2bin_i])).GetValue() == 0) {
        if (vdm_dec2bin_b.OutOfRange(1)) {
          CGUTIL::RunTime(L"Illegal index");
        }
        var1_15 = Bool((static_cast<Int>(vdm_dec2bin_b[1])).GetValue() == 1);
      }
      else {
        var1_15 = Bool(false);
      }
      if (var1_15.GetValue()) {
        Sequence tmpSeq_30;
        for (int count_31 = 1; count_31 <= vdm_dec2bin_b.Length(); count_31++) {
          Int vdm_dec2bin_i_1 (count_31);
          if (vdm_dec2bin_b.OutOfRange(vdm_dec2bin_i_1.GetValue())) {
            CGUTIL::RunTime(L"Illegal index");
          }
          tmpSeq_30.ImpAppend(static_cast<Int>(vdm_dec2bin_b[vdm_dec2bin_i_1]) * Int(2).Exp(Int(vdm_dec2bin_b.Length()) - vdm_dec2bin_i_1));
        }
        var2_14 = Bool(vdm_dec2bin_X.GetValue() == vdm_dec2bin_NatSeqSum(tmpSeq_30).GetValue());
      }
      else {
        var2_14 = Bool(false);
      }
      pred_8 = var2_14;
    }
    else {
      pred_8 = Bool(true);
    }
    if (!(pred_8.GetValue())) {
      tmpQuant_4 = false;
    }
  }
  return Bool(tmpQuant_4);
}

#endif // DEF_dec2bin_post_dec2bin

#ifndef DEF_dec2bin_NatSeqSum

Int vdm_dec2bin_NatSeqSum (const type_iL &vdm_dec2bin_s) {
  Int varRes_2;
  bool succ_3 = false;
  if ((succ_3 = (vdm_dec2bin_s.IsEmpty()))) {
    varRes_2 = Int(0);
  }
  if (!succ_3) {
    varRes_2 = static_cast<Int>(vdm_dec2bin_s.Hd()) + vdm_dec2bin_NatSeqSum(vdm_dec2bin_s);
  }
  return varRes_2;
}

#endif // DEF_dec2bin_NatSeqSum


