//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/dec2bin.vdmsl".

#ifndef _dec2bin_h
#define _dec2bin_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "dec2bin_anonym.h"


void init_dec2bin ();

type_iL vdm_dec2bin_dec2bin (const Int &);

Bool vdm_dec2bin_pre_dec2bin (const Int &);

Bool vdm_dec2bin_post_dec2bin (const Int &, const type_iL &);

Int vdm_dec2bin_NatSeqSum (const type_iL &);


#endif // _dec2bin_h
