//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/exchangeFn.vdmsl".


#include "exchangeFn.h"

#include "exchangeFn_userimpl.cpp"


void init_exchangeFn () {}

#ifndef DEF_exchangeFn_post_exchangeFn

Bool vdm_exchangeFn_post_exchangeFn (const type_ii2P &vdm_exchangeFn_t, const type_ii2P &vdm_exchangeFn_z) {
  Bool varRes_3;
  const Int vdm_exchangeFn_x (vdm_exchangeFn_t.GetInt(1));
  const Int vdm_exchangeFn_y (vdm_exchangeFn_t.GetInt(2));
  varRes_3 = Bool(vdm_exchangeFn_z == mk_(vdm_exchangeFn_y, vdm_exchangeFn_x));
  return varRes_3;
}

#endif // DEF_exchangeFn_post_exchangeFn


