//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:\\VDM-SL\\studyingProgramSpecification\\chap4\\exchangeOp.vdmsl".

#ifndef _exchangeOp_h
#define _exchangeOp_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "exchangeOp_anonym.h"


enum {
  vdm_exchangeOp_vars = TAG_TYPE_exchangeOp_vars,
  length_exchangeOp_vars = 2,
  pos_exchangeOp_vars_x = 1,
  pos_exchangeOp_vars_y = 2
};

class TYPE_exchangeOp_vars : public Record {
public:
  TYPE_exchangeOp_vars () : Record(TAG_TYPE_exchangeOp_vars, 2) {}

  TYPE_exchangeOp_vars &Init (const Int &p1, const Int &p2);
  TYPE_exchangeOp_vars (const Common &c) : Record(c) {}

  const wchar_t * GetTypeName () const   {
    return L"TYPE_exchangeOp_vars";
  }

  Int get_x () const;
  void set_x (const Int &p);
  Int get_y () const;
  void set_y (const Int &p);
};

void init_exchangeOp ();

void vdm_exchangeOp_exchange ();

Bool vdm_exchangeOp_post_exchange (const TYPE_exchangeOp_vars &, const TYPE_exchangeOp_vars &);


#endif // _exchangeOp_h
