//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/exchangeFn.vdmsl".

#ifndef _exchangeFn_h
#define _exchangeFn_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "exchangeFn_anonym.h"


void init_exchangeFn ();

type_ii2P vdm_exchangeFn_exchangeFn (const type_ii2P &);

Bool vdm_exchangeFn_post_exchangeFn (const type_ii2P &, const type_ii2P &);


#endif // _exchangeFn_h
