//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/exponent.vdmsl".

#ifndef _exponent_h
#define _exponent_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "exponent_anonym.h"


void init_exponent ();

Int vdm_exponent_exponent (const Int &, const Int &);


#endif // _exponent_h
