//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/exponent.vdmsl".


#include "exponent.h"


#ifdef DEF_exponent_USERIMPL

#include "exponent_userimpl.cpp"


#endif // DEF_exponent_USERIMPL


void init_exponent () {}

#ifndef DEF_exponent_exponent

Int vdm_exponent_exponent (const Int &vdm_exponent_m, const Int &vdm_exponent_n) {
  return vdm_exponent_m.Exp(vdm_exponent_n);
}

#endif // DEF_exponent_exponent


