//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/gcd.vdmsl".

#ifndef _gcd_h
#define _gcd_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "gcd_anonym.h"


void init_gcd ();

type_iS vdm_gcd_Cds (const Int &, const Int &);

Bool vdm_gcd_post_Cds (const Int &, const Int &, const type_iS &);

Int vdm_gcd_Max (const type_iS &);

Bool vdm_gcd_post_Max (const type_iS &, const Int &);

Int vdm_gcd_gcd (const Int &, const Int &);

Bool vdm_gcd_post_gcd (const Int &, const Int &, const Int &);


#endif // _gcd_h
