//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-26 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/gcd.vdmsl".


#include "gcd.h"

#include "gcd_userimpl.cpp"


void init_gcd () {}

#ifndef DEF_gcd_post_Cds

Bool vdm_gcd_post_Cds (const Int &vdm_gcd_x, const Int &vdm_gcd_y, const type_iS &vdm_gcd_nset) {
  bool tmpQuant_5 = true;
  Set tmpSet_11 (vdm_gcd_nset);
  Generic tmpe_10;
  for (bool bb_9 = tmpSet_11.First(tmpe_10); bb_9 && tmpQuant_5; bb_9 = tmpSet_11.Next(tmpe_10)) {
    const Int vdm_gcd_z (tmpe_10);
    bool tmpQuant_8 = false;
    CGUTIL::NotSupported(L"type bind");
    if (!tmpQuant_8) {
      tmpQuant_5 = false;
    }
  }
  return Bool(tmpQuant_5);
}

#endif // DEF_gcd_post_Cds

#ifndef DEF_gcd_post_Max

Bool vdm_gcd_post_Max (const type_iS &vdm_gcd_ns, const Int &vdm_gcd_mx) {
  Bool varRes_3;
  if (vdm_gcd_ns.InSet(vdm_gcd_mx)) {
    bool tmpQuant_8 = true;
    Set tmpSet_15 (vdm_gcd_ns);
    Generic tmpe_14;
    for (bool bb_13 = tmpSet_15.First(tmpe_14); bb_13 && tmpQuant_8; bb_13 = tmpSet_15.Next(tmpe_14)) {
      const Int vdm_gcd_n (tmpe_14);
      if (!(vdm_gcd_mx.GetValue() >= vdm_gcd_n.GetValue())) {
        tmpQuant_8 = false;
      }
    }
    varRes_3 = Bool(tmpQuant_8);
  }
  else {
    varRes_3 = Bool(false);
  }
  return varRes_3;
}

#endif // DEF_gcd_post_Max

#ifndef DEF_gcd_post_gcd

Bool vdm_gcd_post_gcd (const Int &vdm_gcd_x, const Int &vdm_gcd_y, const Int &vdm_gcd_z) {
  return Bool(vdm_gcd_z.GetValue() == vdm_gcd_Max(vdm_gcd_Cds(vdm_gcd_x, vdm_gcd_y)).GetValue());
}

#endif // DEF_gcd_post_gcd


