//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/innerprod.vdmsl".

#ifndef _innerprod_h
#define _innerprod_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "innerprod_anonym.h"


void init_innerprod ();

Int vdm_innerprod_IntSeqSum (const type_iL &);

Int vdm_innerprod_innerprod (const type_iL &, const type_iL &);

Bool vdm_innerprod_pre_innerprod (const type_iL &, const type_iL &);


#endif // _innerprod_h
