//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/MagicSqr.vdmsl".

#ifndef _MagicSqr_h
#define _MagicSqr_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "MagicSqr_anonym.h"


void init_MagicSqr ();

type_iLL vdm_MagicSqr_MagicSqr ();

Bool vdm_MagicSqr_post_MagicSqr (const type_iLL &);

Int vdm_MagicSqr_NatSeqSum (const type_iL &);


#endif // _MagicSqr_h
