//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/maximum.vdmsl".

#ifndef _maximum_h
#define _maximum_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "maximum_anonym.h"


void init_maximum ();

Int vdm_maximum_maximum (const Int &, const type_iL &);

Bool vdm_maximum_pre_maximum (const Int &, const type_iL &);

Bool vdm_maximum_post_maximum (const Int &, const type_iL &, const Int &);


#endif // _maximum_h
