//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/MaxIncSubSeq.vdmsl".


#include "MaxIncSubSeq.h"

#include "MaxIncSubSeq_userimpl.cpp"


void init_MaxIncSubSeq () {}

#ifndef DEF_MaxIncSubSeq_IncSubSeq

Bool vdm_MaxIncSubSeq_IncSubSeq (const type_iL &vdm_MaxIncSubSeq_X, const Int &vdm_MaxIncSubSeq_k, const Int &vdm_MaxIncSubSeq_h) {
  Bool varRes_4;
  if ((1 <= vdm_MaxIncSubSeq_k.GetValue()) ? ((vdm_MaxIncSubSeq_k + vdm_MaxIncSubSeq_h).GetValue() <= vdm_MaxIncSubSeq_X.Length()) : false) {
    bool tmpQuant_16 = true;
    const Set e1_set_19 (vdm_MaxIncSubSeq_X.Inds());
    Set tmpSet_46 (e1_set_19);
    Generic tmpe_45;
    for (bool bb_44 = tmpSet_46.First(tmpe_45); bb_44 && tmpQuant_16; bb_44 = tmpSet_46.Next(tmpe_45)) {
      const Int vdm_MaxIncSubSeq_m (tmpe_45);
      Set tmpSet_43 (e1_set_19);
      Generic tmpe_42;
      for (bool bb_41 = tmpSet_43.First(tmpe_42); bb_41 && tmpQuant_16; bb_41 = tmpSet_43.Next(tmpe_42)) {
        const Int vdm_MaxIncSubSeq_l (tmpe_42);
        if (!((((vdm_MaxIncSubSeq_k.GetValue() <= vdm_MaxIncSubSeq_l.GetValue()) ? (vdm_MaxIncSubSeq_l.GetValue() < vdm_MaxIncSubSeq_m.GetValue()) : false) ? (vdm_MaxIncSubSeq_m.GetValue() <= (vdm_MaxIncSubSeq_k + vdm_MaxIncSubSeq_h).GetValue()) : false) ? ((static_cast<Int>(vdm_MaxIncSubSeq_X[vdm_MaxIncSubSeq_l])).GetValue() <= (static_cast<Int>(vdm_MaxIncSubSeq_X[vdm_MaxIncSubSeq_m])).GetValue()) : true)) {
          tmpQuant_16 = false;
        }
      }
    }
    varRes_4 = Bool(tmpQuant_16);
  }
  else {
    varRes_4 = Bool(false);
  }
  return varRes_4;
}

#endif // DEF_MaxIncSubSeq_IncSubSeq

#ifndef DEF_MaxIncSubSeq_post_MaxIncSubSeq

Bool vdm_MaxIncSubSeq_post_MaxIncSubSeq (const type_iL &vdm_MaxIncSubSeq_X, const type_ii2P &vdm_MaxIncSubSeq_z) {
  Bool varRes_3;
  const Int vdm_MaxIncSubSeq_q (vdm_MaxIncSubSeq_z.GetInt(1));
  const Int vdm_MaxIncSubSeq_p (vdm_MaxIncSubSeq_z.GetInt(2));
  if (vdm_MaxIncSubSeq_IncSubSeq(vdm_MaxIncSubSeq_X, vdm_MaxIncSubSeq_q, vdm_MaxIncSubSeq_p).GetValue()) {
    bool tmpQuant_11 = true;
    const Set e1_set_14 (vdm_MaxIncSubSeq_X.Inds());
    Set tmpSet_39 (e1_set_14);
    Generic tmpe_38;
    for (bool bb_37 = tmpSet_39.First(tmpe_38); bb_37 && tmpQuant_11; bb_37 = tmpSet_39.Next(tmpe_38)) {
      const Int vdm_MaxIncSubSeq_k (tmpe_38);
      bool tmpQuant_16 = true;
      Set e_set_17 = Set();
      int ubi_25 = (Int(vdm_MaxIncSubSeq_X.Length()) - Int(1)).GetValue();
      for (int count_23 = 1; count_23 <= ubi_25; count_23++) {
        e_set_17.Insert(Int(count_23));
      }
      Set tmpSet_36 (e_set_17);
      Generic tmpe_35;
      for (bool bb_34 = tmpSet_36.First(tmpe_35); bb_34 && tmpQuant_16; bb_34 = tmpSet_36.Next(tmpe_35)) {
        const Int vdm_MaxIncSubSeq_h (tmpe_35);
        if (!(vdm_MaxIncSubSeq_IncSubSeq(vdm_MaxIncSubSeq_X, vdm_MaxIncSubSeq_k, vdm_MaxIncSubSeq_h).GetValue() ? (vdm_MaxIncSubSeq_p.GetValue() >= vdm_MaxIncSubSeq_h.GetValue()) : true)) {
          tmpQuant_16 = false;
        }
      }
      if (!tmpQuant_16) {
        tmpQuant_11 = false;
      }
    }
    varRes_3 = Bool(tmpQuant_11);
  }
  else {
    varRes_3 = Bool(false);
  }
  return varRes_3;
}

#endif // DEF_MaxIncSubSeq_post_MaxIncSubSeq


