//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/MaxIncSubSeq.vdmsl".

#ifndef _MaxIncSubSeq_h
#define _MaxIncSubSeq_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "MaxIncSubSeq_anonym.h"


void init_MaxIncSubSeq ();

Bool vdm_MaxIncSubSeq_IncSubSeq (const type_iL &, const Int &, const Int &);

type_ii2P vdm_MaxIncSubSeq_MaxIncSubSeq (const type_iL &);

Bool vdm_MaxIncSubSeq_post_MaxIncSubSeq (const type_iL &, const type_ii2P &);


#endif // _MaxIncSubSeq_h
