//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/MinSubSeqSum.vdmsl".


#include "MinSubSeqSum.h"

#include "MinSubSeqSum_userimpl.cpp"


void init_MinSubSeqSum () {}

#ifndef DEF_MinSubSeqSum_IntSeqSum

Int vdm_MinSubSeqSum_IntSeqSum (const type_iL &vdm_MinSubSeqSum_s) {
  return ((vdm_MinSubSeqSum_s == Sequence()) ? Int(0) : static_cast<Int>(vdm_MinSubSeqSum_s.Hd()) + vdm_MinSubSeqSum_IntSeqSum(vdm_MinSubSeqSum_s.Tl()));
}

#endif // DEF_MinSubSeqSum_IntSeqSum

#ifndef DEF_MinSubSeqSum_pre_MinSubSeqSum

Bool vdm_MinSubSeqSum_pre_MinSubSeqSum (const type_iL &vdm_MinSubSeqSum_X) {
  return Bool(vdm_MinSubSeqSum_X.Length() >= 1);
}

#endif // DEF_MinSubSeqSum_pre_MinSubSeqSum

#ifndef DEF_MinSubSeqSum_post_MinSubSeqSum

Bool vdm_MinSubSeqSum_post_MinSubSeqSum (const type_iL &vdm_MinSubSeqSum_X, const type_ii2P &vdm_MinSubSeqSum_z) {
  Bool varRes_3;
  const Int vdm_MinSubSeqSum_i (vdm_MinSubSeqSum_z.GetInt(1));
  const Int vdm_MinSubSeqSum_j (vdm_MinSubSeqSum_z.GetInt(2));
  if (((1 <= vdm_MinSubSeqSum_i.GetValue()) ? (vdm_MinSubSeqSum_i.GetValue() <= vdm_MinSubSeqSum_j.GetValue()) : false) ? (vdm_MinSubSeqSum_j.GetValue() <= vdm_MinSubSeqSum_X.Length()) : false) {
    bool tmpQuant_19 = true;
    const Set e1_set_22 (vdm_MinSubSeqSum_X.Inds());
    Set tmpSet_43 (e1_set_22);
    Generic tmpe_42;
    for (bool bb_41 = tmpSet_43.First(tmpe_42); bb_41 && tmpQuant_19; bb_41 = tmpSet_43.Next(tmpe_42)) {
      const Int vdm_MinSubSeqSum_m (tmpe_42);
      Set tmpSet_40 (e1_set_22);
      Generic tmpe_39;
      for (bool bb_38 = tmpSet_40.First(tmpe_39); bb_38 && tmpQuant_19; bb_38 = tmpSet_40.Next(tmpe_39)) {
        const Int vdm_MinSubSeqSum_l (tmpe_39);
        if (!(vdm_MinSubSeqSum_IntSeqSum(vdm_MinSubSeqSum_X.SubSequence(vdm_MinSubSeqSum_i.GetValue(), vdm_MinSubSeqSum_j.GetValue())).GetValue() <= vdm_MinSubSeqSum_IntSeqSum(vdm_MinSubSeqSum_X.SubSequence(vdm_MinSubSeqSum_l.GetValue(), vdm_MinSubSeqSum_m.GetValue())).GetValue())) {
          tmpQuant_19 = false;
        }
      }
    }
    varRes_3 = Bool(tmpQuant_19);
  }
  else {
    varRes_3 = Bool(false);
  }
  return varRes_3;
}

#endif // DEF_MinSubSeqSum_post_MinSubSeqSum


