//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/MinSubSeqSum.vdmsl".

#ifndef _MinSubSeqSum_h
#define _MinSubSeqSum_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "MinSubSeqSum_anonym.h"


void init_MinSubSeqSum ();

Int vdm_MinSubSeqSum_IntSeqSum (const type_iL &);

type_ii2P vdm_MinSubSeqSum_MinSubSeqSum (const type_iL &);

Bool vdm_MinSubSeqSum_pre_MinSubSeqSum (const type_iL &);

Bool vdm_MinSubSeqSum_post_MinSubSeqSum (const type_iL &, const type_ii2P &);


#endif // _MinSubSeqSum_h
