//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-24 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/mult.vdmsl".

#ifndef _mult_h
#define _mult_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "mult_anonym.h"


void init_mult ();

Int vdm_mult_mult (const Int &, const Int &);

Bool vdm_mult_pre_mult (const Int &, const Int &);


#endif // _mult_h
