//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-24 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/mult.vdmsl".


#include "mult.h"


#ifdef DEF_mult_USERIMPL

#include "mult_userimpl.cpp"


#endif // DEF_mult_USERIMPL


void init_mult () {}

#ifndef DEF_mult_mult

Int vdm_mult_mult (const Int &vdm_mult_x, const Int &vdm_mult_y) {
  if (!vdm_mult_pre_mult(vdm_mult_x, vdm_mult_y).GetValue()) {
    CGUTIL::RunTime(L"Precondition failure in mult");
  }
  return vdm_mult_x * vdm_mult_y;
}

#endif // DEF_mult_mult

#ifndef DEF_mult_pre_mult

Bool vdm_mult_pre_mult (const Int &vdm_mult_x, const Int &vdm_mult_y) {
  return Bool(vdm_mult_x.GetValue() > 0);
}

#endif // DEF_mult_pre_mult


