//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-30 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/nqueens.vdmsl".

#ifndef _nqueens_h
#define _nqueens_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "nqueens_anonym.h"


void init_nqueens ();

type_iL vdm_nqueens_nqueens (const Int &);

Bool vdm_nqueens_post_nqueens (const Int &, const type_iL &);


#endif // _nqueens_h
