//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-30 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/nqueens.vdmsl".


#include "nqueens.h"

#include "nqueens_userimpl.cpp"


void init_nqueens () {}

#ifndef DEF_nqueens_post_nqueens

Bool vdm_nqueens_post_nqueens (const Int &vdm_nqueens_n, const type_iL &vdm_nqueens_X) {
  Bool varRes_3;
  Bool var1_4;
  if (vdm_nqueens_X.Length() == vdm_nqueens_n.GetValue()) {
    bool tmpQuant_10 = true;
    const Set e1_set_13 (vdm_nqueens_X.Inds());
    Set tmpSet_27 (e1_set_13);
    Generic tmpe_26;
    for (bool bb_25 = tmpSet_27.First(tmpe_26); bb_25 && tmpQuant_10; bb_25 = tmpSet_27.Next(tmpe_26)) {
      const Int vdm_nqueens_i (tmpe_26);
      if (!((1 <= (static_cast<Int>(vdm_nqueens_X[vdm_nqueens_i])).GetValue()) ? ((static_cast<Int>(vdm_nqueens_X[vdm_nqueens_i])).GetValue() <= vdm_nqueens_n.GetValue()) : false)) {
        tmpQuant_10 = false;
      }
    }
    var1_4 = Bool(tmpQuant_10);
  }
  else {
    var1_4 = Bool(false);
  }
  if (var1_4.GetValue()) {
    bool tmpQuant_29 = true;
    const Set e1_set_32 (vdm_nqueens_X.Inds());
    Set tmpSet_74 (e1_set_32);
    Generic tmpe_73;
    for (bool bb_72 = tmpSet_74.First(tmpe_73); bb_72 && tmpQuant_29; bb_72 = tmpSet_74.Next(tmpe_73)) {
      const Int vdm_nqueens_j (tmpe_73);
      Set tmpSet_71 (e1_set_32);
      Generic tmpe_70;
      for (bool bb_69 = tmpSet_71.First(tmpe_70); bb_69 && tmpQuant_29; bb_69 = tmpSet_71.Next(tmpe_70)) {
        const Int vdm_nqueens_i (tmpe_70);
        if (!((!(vdm_nqueens_i.GetValue() == vdm_nqueens_j.GetValue())) ? !((((static_cast<Int>(vdm_nqueens_X[vdm_nqueens_i])).GetValue() == (static_cast<Int>(vdm_nqueens_X[vdm_nqueens_j])).GetValue()) ? true : ((vdm_nqueens_i + static_cast<Int>(vdm_nqueens_X[vdm_nqueens_i])).GetValue() == (vdm_nqueens_j + static_cast<Int>(vdm_nqueens_X[vdm_nqueens_j])).GetValue())) ? true : ((vdm_nqueens_i + static_cast<Int>(vdm_nqueens_X[vdm_nqueens_j])).GetValue() == (vdm_nqueens_j + static_cast<Int>(vdm_nqueens_X[vdm_nqueens_i])).GetValue())) : true)) {
          tmpQuant_29 = false;
        }
      }
    }
    varRes_3 = Bool(tmpQuant_29);
  }
  else {
    varRes_3 = Bool(false);
  }
  return varRes_3;
}

#endif // DEF_nqueens_post_nqueens


