//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/parindrome.vdmsl".

#ifndef _parindrome_h
#define _parindrome_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "parindrome_anonym.h"


void init_parindrome ();

type_iL vdm_parindrome_parindrome ();

Bool vdm_parindrome_post_parindrome (const type_iL &);


#endif // _parindrome_h
