//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-24 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/Quotient.vdmsl".


#include "Quotient.h"

#include "Quotient_userimpl.cpp"


void init_Quotient () {}

#ifndef DEF_Quotient_pre_Quotient

Bool vdm_Quotient_pre_Quotient (const Int &vdm_Quotient_x, const Int &vdm_Quotient_y) {
  return Bool(vdm_Quotient_y.GetValue() > 0);
}

#endif // DEF_Quotient_pre_Quotient

#ifndef DEF_Quotient_post_Quotient

Bool vdm_Quotient_post_Quotient (const Int &vdm_Quotient_x, const Int &vdm_Quotient_y, const type_ii2P &vdm_Quotient_z) {
  Bool varRes_4;
  const Int vdm_Quotient_q (vdm_Quotient_z.GetInt(1));
  const Int vdm_Quotient_r (vdm_Quotient_z.GetInt(2));
  varRes_4 = Bool(((vdm_Quotient_x.GetValue() == (vdm_Quotient_q * vdm_Quotient_y + vdm_Quotient_r).GetValue()) ? (0 <= vdm_Quotient_r.GetValue()) : false) ? (vdm_Quotient_r.GetValue() < vdm_Quotient_y.GetValue()) : false);
  return varRes_4;
}

#endif // DEF_Quotient_post_Quotient


