//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-24 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/Quotient.vdmsl".

#ifndef _Quotient_h
#define _Quotient_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "Quotient_anonym.h"


void init_Quotient ();

type_ii2P vdm_Quotient_Quotient (const Int &, const Int &);

Bool vdm_Quotient_pre_Quotient (const Int &, const Int &);

Bool vdm_Quotient_post_Quotient (const Int &, const Int &, const type_ii2P &);


#endif // _Quotient_h
