//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/reverseArray.vdmsl".

#ifndef _reverseArray_h
#define _reverseArray_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "reverseArray_anonym.h"


enum {
  vdm_reverseArray_array = TAG_TYPE_reverseArray_array,
  length_reverseArray_array = 2,
  pos_reverseArray_array_n = 1,
  pos_reverseArray_array_X = 2
};

class TYPE_reverseArray_array : public Record {
public:
  TYPE_reverseArray_array () : Record(TAG_TYPE_reverseArray_array, 2) {}

  TYPE_reverseArray_array &Init (const Int &p1, const type_iL &p2);
  TYPE_reverseArray_array (const Common &c) : Record(c) {}

  const wchar_t * GetTypeName () const   {
    return L"TYPE_reverseArray_array";
  }

  Int get_n () const;
  void set_n (const Int &p);
  type_iL get_X () const;
  void set_X (const type_iL &p);
};

void init_reverseArray ();

void vdm_reverseArray_reverseArray ();

Bool vdm_reverseArray_pre_reverseArray (const TYPE_reverseArray_array &);

Bool vdm_reverseArray_post_reverseArray (const TYPE_reverseArray_array &, const TYPE_reverseArray_array &);


#endif // _reverseArray_h
