//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/sqroot.vdmsl".

#ifndef _sqroot_h
#define _sqroot_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "sqroot_anonym.h"


void init_sqroot ();

Int vdm_sqroot_sqroot (const Int &);

Bool vdm_sqroot_pre_sqroot (const Int &);

Bool vdm_sqroot_post_sqroot (const Int &, const Int &);


#endif // _sqroot_h
