//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-28 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:/VDM-SL/studyingProgramSpecification/chap4/sqroot.vdmsl".


#include "sqroot.h"

#include "sqroot_userimpl.cpp"


void init_sqroot () {}

#ifndef DEF_sqroot_pre_sqroot

Bool vdm_sqroot_pre_sqroot (const Int &vdm_sqroot_x) {
  return Bool(vdm_sqroot_x.GetValue() >= 0);
}

#endif // DEF_sqroot_pre_sqroot

#ifndef DEF_sqroot_post_sqroot

Bool vdm_sqroot_post_sqroot (const Int &vdm_sqroot_x, const Int &vdm_sqroot_z) {
  return Bool(((vdm_sqroot_z.Exp(Int(2)).GetValue() <= vdm_sqroot_x.GetValue()) ? (vdm_sqroot_x.GetValue() < (vdm_sqroot_z + Int(1)).Exp(Int(2)).GetValue()) : false) ? (vdm_sqroot_z.GetValue() >= 0) : false);
}

#endif // DEF_sqroot_post_sqroot


