//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-24 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:\\VDM-SL\\studyingProgramSpecification\\chap4\\summation.vdmsl".

#ifndef _summation_h
#define _summation_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "summation_anonym.h"


void init_summation ();

Int vdm_summation_NatSeqSum (const type_iL &);

Int vdm_summation_Summation (const Int &, const type_iL &);

Bool vdm_summation_pre_Summation (const Int &, const type_iL &);

Bool vdm_summation_post_Summation (const Int &, const type_iL &, const Int &);


#endif // _summation_h
