//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2020-08-24 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
// This file was genereted from "E:\\VDM-SL\\studyingProgramSpecification\\chap4\\summation.vdmsl".


#include "summation.h"

#include "summation_userimpl.cpp"


void init_summation () {}

#ifndef DEF_summation_NatSeqSum

Int vdm_summation_NatSeqSum (const type_iL &vdm_summation_s) {
  Int varRes_2;
  bool succ_3 = false;
  if ((succ_3 = (vdm_summation_s.IsEmpty()))) {
    varRes_2 = Int(0);
  }
  if (!succ_3) {
    varRes_2 = static_cast<Int>(vdm_summation_s.Hd()) + vdm_summation_NatSeqSum(vdm_summation_s);
  }
  return varRes_2;
}

#endif // DEF_summation_NatSeqSum

#ifndef DEF_summation_pre_Summation

Bool vdm_summation_pre_Summation (const Int &vdm_summation_n, const type_iL &vdm_summation_a) {
  return Bool((vdm_summation_n.GetValue() == vdm_summation_a.Length()) ? (vdm_summation_n.GetValue() >= 1) : false);
}

#endif // DEF_summation_pre_Summation

#ifndef DEF_summation_post_Summation

Bool vdm_summation_post_Summation (const Int &vdm_summation_n, const type_iL &vdm_summation_a, const Int &vdm_summation_s) {
  return Bool(vdm_summation_s.GetValue() == vdm_summation_NatSeqSum(vdm_summation_a).GetValue());
}

#endif // DEF_summation_post_Summation


